# Generated by Django 4.2.11 on 2025-12-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0021_socio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
